
server:
  servlet.context-path: "/parking-service"
  port: ${RATE_LIMITER_APP_PORT:8080}

spring.jpa.hibernate.ddl-auto : update
spring.datasource.url: "jdbc:mysql://${MYSQL_HOST:localhost}:3306/db_example"
spring.datasource.username: springuser
spring.datasource.password: ThePassword

logging.level:
  com.pkd: ${APP_PACKAGE_LOGGING_LEVEL:INFO}
  org.springframework: ${LIBRARY_LOGGING_LEVEL:INFO}
logging.pattern.console: "[%date{dd-MMM-yyyy_HH:mm:ss.SSS} | %thread] %-5level %logger[%method] : %message%n"